"""
qa.py — QA Agent for de-agent-studio
Reviews pipeline files generated by Builder Agent
Returns structured QA report with severity levels
"""

import anthropic
import os
import json
from dotenv import load_dotenv
from tools.file_tools import read_file

load_dotenv()

# ─────────────────────────────────────────
# SYSTEM PROMPT
# ─────────────────────────────────────────
QA_SYSTEM_PROMPT = """You are a Senior QA Engineer at Peacock TV
specializing in data pipeline quality assurance.
You have deep expertise in SQL, PySpark, Airflow, and Databricks best practices.

You receive pipeline files and the original user requirement.
Your job is to independently review the code and return a structured QA report.

Step 1 — Read all pipeline files:
→ call read_file() for each file in the build result
→ read DAG, notebook, config, and SQL files

Step 2 — Review against original requirement:
→ does the logic match what user asked for?
→ are the correct tables being used?
→ is the output table named correctly?
→ is the schedule correct?

Step 3 — Check each component:

Syntax:
→ valid SQL/Python/YAML syntax?
→ no missing keywords or brackets?
→ correct indentation?

Coding standards:
→ naming conventions followed?
→ proper comments and documentation?
→ error handling present?
→ Slack alerts configured?

Logic soundness:
→ joins are correct?
→ filters make sense?
→ aggregations are accurate?
→ edge cases handled?

Performance:
→ any obvious optimization opportunities?
→ missing partitioning?
→ unnecessary SELECT *?
→ missing LIMIT on large tables?

Step 4 — Return structured report:

Always return response as JSON only, no other text:
{
    "overall_status": "pass" or "fail",
    "pipeline_name": "...",
    "critical": [
        {
            "file": "filename",
            "issue": "description of issue",
            "suggestion": "how to fix"
        }
    ],
    "warnings": [
        {
            "file": "filename",
            "issue": "description",
            "suggestion": "improvement"
        }
    ],
    "suggestions": [
        {
            "file": "filename",
            "issue": "description",
            "suggestion": "enhancement"
        }
    ],
    "summary": "overall assessment in 2-3 sentences"
}

Rules:
→ critical: must fix before deploying
→ warnings: should fix, not blocking
→ suggestions: nice to have, optional
→ if any critical issues: overall_status = "fail"
→ if only warnings/suggestions: overall_status = "pass"
"""

# ─────────────────────────────────────────
# TOOL DEFINITIONS
# ─────────────────────────────────────────
QA_TOOLS = [
    {
        "name": "read_file",
        "description": "Read content of a generated pipeline file for review. Call this for each file in the build result before starting QA review.",
        "input_schema": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string",
                    "description": "Name of file to read e.g. subscribers_dag.py"
                }
            },
            "required": ["filename"]
        }
    }
]

# ─────────────────────────────────────────
# TOOL EXECUTOR
# ─────────────────────────────────────────
def execute_qa_tool(tool_name: str, tool_input: dict) -> str:
    if tool_name == "read_file":
        return read_file(tool_input["filename"])
    return f"Unknown tool: {tool_name}"

# ─────────────────────────────────────────
# QA AGENT
# ─────────────────────────────────────────
def run_qa(builder_result: dict, original_request: str) -> dict:
    """
    Run QA Agent on built pipeline files.
    Returns structured QA report as dict.
    """
    client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

    # build message with context
    qa_message = f"""
Original user requirement:
{original_request}

Builder result:
{json.dumps(builder_result, indent=2)}

Please review all files listed in files_created
and return a complete QA report.
"""

    messages = [{"role": "user", "content": qa_message}]

    while True:
        response = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=4096,
            system=QA_SYSTEM_PROMPT,
            tools=QA_TOOLS,
            messages=messages
        )

        if response.stop_reason == "tool_use":
            messages.append({
                "role": "assistant",
                "content": response.content
            })
            tool_results = []
            for block in response.content:
                if block.type == "tool_use":
                    result = execute_qa_tool(block.name, block.input)
                    tool_results.append({
                        "type": "tool_result",
                        "tool_use_id": block.id,
                        "content": result
                    })
            messages.append({
                "role": "user",
                "content": tool_results
            })

        elif response.stop_reason == "end_turn":
            reply = "".join(
                block.text for block in response.content
                if hasattr(block, "text")
            )
            try:
                result = json.loads(reply)
            except json.JSONDecodeError:
                import re
                json_match = re.search(r'\{.*\}', reply, re.DOTALL)
                if json_match:
                    result = json.loads(json_match.group())
                else:
                    result = {
                        "overall_status": "error",
                        "summary": reply
                    }
            return result